---
apiVersion: batch/v1
kind: Job
metadata:
  name: dkubeadm-{{ required "Please fill up the correct value for operation !!" .Values.opration }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: dkubeadm-ctr
        image: ocdr/dkubeadm:{{ required "Please fill up the correct value for dkubeadm_version !!" .Values.dkubeadm_version }}
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          /opt/dkubeadm/dkubeadm.sh dkube {{ required "Please fill up the correct value for operation !!" .Values.opration }}
        volumeMounts:
          - mountPath: /mnt/tmp
            name: tmp
          - 
            mountPath: /root/.dkube/dkube.ini
            name: dkubeini
            subPath: dkube.ini

      restartPolicy: Never
      serviceAccountName: dkubeadm-sa
      volumes:
        -
          hostPath:
            path: /tmp
          name: tmp
        - 
          configMap:
            name: dkube-ini
          name: dkubeini
