---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod-ctr
    image: ubuntu:18.04
    command: 
    - bash
    - -c
    - |
      echo "Hello World..."
      sleep 1000000000000000
